import { z } from 'zod';
import { marketDataSchema } from '../schemas/index.js';

export type MarketData = z.infer<typeof marketDataSchema>;

// Generated by https://quicktype.io

export interface MarketstackAPIResponse {
  pagination: Pagination;
  data: Datum[];
}

interface Datum {
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  adj_high: number;
  adj_low: number;
  adj_close: number;
  adj_open: number;
  adj_volume: number;
  split_factor: number;
  dividend: number;
  symbol: string;
  exchange: string;
  date: string;
}

interface Pagination {
  limit: number;
  offset: number;
  count: number;
  total: number;
}
