// import { z } from 'zod';
// import {
//   fundamentalSchema,
//   fundamentalsSchema,
//   marketDataSchema,
//   marketDatumSchema,
//   tickerSchema,
//   tickersSchema,
//   strategiesSchema,
//   strategySchema,
//   quoteSchema,
// } from '../schemas/index.js';

// export type MarketData = z.infer<typeof marketDataSchema>;
// export type MarketDatum = z.infer<typeof marketDatumSchema>;
// export type Ticker = z.infer<typeof tickerSchema>;
// export type Tickers = z.infer<typeof tickersSchema>;
// export type Fundamental = z.infer<typeof fundamentalSchema>;
// export type Fundamentals = z.infer<typeof fundamentalsSchema>;
// export type Strategies = z.infer<typeof strategiesSchema>;
// export type Strategy = z.infer<typeof strategySchema>;
// export type Quote = z.infer<typeof quoteSchema>;

// import JobsProvider from '../jobs_provider/index.js';
import {
  marketDatumSchema,
  marketDataSchema,
  tickerSchema,
  tickersSchema,
  strategySignalSchema,
  strategySignalsSchema,
  strategySignalResponseSchema,
  strategySignalsResponseSchema,
  strategySchema,
  strategiesSchema,
  strategyTickerDatumSchema,
  strategyTickerDataSchema,
  marketDataInformationSchema,
  tradeSchema,
  tradesSchema,
  placedTradeSchema,
  placedTradesSchema,
  jobSchema,
  jobsSchema,
  jobsResponseSchema,
} from '../schemas/index.js';

import { z } from 'zod';

export type MarketDatum = z.infer<typeof marketDatumSchema>;
export type MarketData = z.infer<typeof marketDataSchema>;
export type Ticker = z.infer<typeof tickerSchema>;
export type Tickers = z.infer<typeof tickersSchema>;
export type MarketDataInformation = z.infer<typeof marketDataInformationSchema>;
export type StrategySignalResponse = z.infer<
  typeof strategySignalResponseSchema
>;
export type StrategySignalsResponse = z.infer<
  typeof strategySignalsResponseSchema
>;
export type StrategySignal = z.infer<typeof strategySignalSchema>;
export type StrategySignals = z.infer<typeof strategySignalsSchema>;
export type Strategy = z.infer<typeof strategySchema>;
export type Strategies = z.infer<typeof strategiesSchema>;
export type StrategyTickerDatum = z.infer<typeof strategyTickerDatumSchema>;
export type StrategyTickerData = z.infer<typeof strategyTickerDataSchema>;
export type Trade = z.infer<typeof tradeSchema>;
export type Trades = z.infer<typeof tradesSchema>;
export type PlacedTrade = z.infer<typeof placedTradeSchema>;
export type PlacedTrades = z.infer<typeof placedTradesSchema>;
// export type PlaceTradesResponse = z.infer<typeof placeTradesResponseSchema>;
export type Job = z.infer<typeof jobSchema>;
export type Jobs = z.infer<typeof jobsSchema>;
export type JobsResponse = z.infer<typeof jobsResponseSchema>;

export { Account } from '../broker_provider/alpaca/entities.js';

// Generated by https://quicktype.io

export interface MarketstackAPIResponse {
  pagination: Pagination;
  data: Datum[];
}

interface Datum {
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  adj_high: number;
  adj_low: number;
  adj_close: number;
  adj_open: number;
  adj_volume: number;
  split_factor: number;
  dividend: number;
  symbol: string;
  exchange: string;
  date: string;
}

interface Pagination {
  limit: number;
  offset: number;
  count: number;
  total: number;
}

// Generated by https://quicktype.io

export interface TiingoAPIResponse {
  date: string;
  close: number;
  high: number;
  low: number;
  open: number;
  volume: number;
  adjClose: number;
  adjHigh: number;
  adjLow: number;
  adjOpen: number;
  adjVolume: number;
  divCash: number;
  splitFactor: number;
}
[];
